In [25]:
import pandas as pd
import os
import datetime as dt

In [2]:
unpickled_df = pd.read_pickle("../../data/clean/twitter_sentiment3.pkl")
unpickled_df

,created_at,screen_name,full_text,id,lang,user_favourites_count,user_followers_count,user_friends_count,user_location,user_profile_image_url,...,mentions,mention_ids,quoted_quote_count,quoted_reply_count,quoted_retweet_count,clean_tokens,compound,negative,neutral,positive
0,2019-10-31 23:58:56+00:00,Ricky_P007,RT @Delta_Exchange: How many coin logos do you...,1190055587255422977,en,532,84,246,"Citeureup, Indonesia",http://pbs.twimg.com/profile_images/1188757498...,...,[Delta_Exchange],[994891951160864769],NaN,NaN,NaN,"[rt, deltaexchange, many, coin, logo, see, ima...",0.0,1.000,0.000,0.0000
1,2019-10-31 23:58:56+00:00,KennedyPattiso1,RT @XRPcryptowolf: Intercontinental Exchange (...,1190055584910991360,en,17182,1051,1969,Liechtenstein,http://pbs.twimg.com/profile_images/3788000000...,...,[XRPcryptowolf],[944462285573099520],NaN,NaN,NaN,"[rt, xrpcryptowolf, intercontinental, exchange...",0.0,0.865,0.135,0.3612
2,2019-10-31 23:58:55+00:00,BtcEthereum,Bitcoin Needs â€˜Real Use Casesâ€™ to Become Digit...,1190055581886775297,en,384,351,526,Cyber Space,http://pbs.twimg.com/profile_images/8792232595...,...,[],[],NaN,NaN,NaN,"[bitcoin, need, real, use, case, become, digit...",0.0,1.000,0.000,0.0000
3,2019-10-31 23:58:52+00:00,erickchan_XLM,@CyhChloe @johnkim77 @jasminecoin @codeyisfun ...,1190055568678895618,en,3051,388,1086,Cambodia,http://pbs.twimg.com/profile_images/1174348587...,...,"[CyhChloe, johnkim77, jasminecoin, codeyisfun,...","[1059871115236073473, 26448153, 11864798016930...",NaN,NaN,NaN,"[cyhchloe, johnkim, jasminecoin, codeyisfun, c...",0.0,0.732,0.268,0.5106
4,2019-10-31 23:58:50+00:00,Researchiing,RT @zerohedge: 11 Years Ago Today Satoshi Naka...,1190055561682964481,en,8,12,30,None,http://abs.twimg.com/sticky/default_profile_im...,...,[zerohedge],[18856867],NaN,NaN,NaN,"[rt, zerohedge, year, ago, today, satoshi, nak...",0.0,1.000,0.000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2019-10-27 13:41:36+00:00,PopME19,RT @satasion: Giveaway Alert! ðŸš¨ No.3\n- Hallow...,1188450678965800960,en,1569,352,1342,None,http://pbs.twimg.com/profile_images/1189525743...,...,"[satasion, satasion]","[1178370879144771585, 1178370879144771585]",NaN,NaN,NaN,"[rt, satasion, giveaway, alert, halloween, edi...",0.0,0.448,0.552,0.9062
4996,2019-10-27 13:41:34+00:00,digifuture1,RT @Lionel46294550: #xrp #xrpcommunity #btc #e...,1188450670157926400,en,318,18,50,United States,http://pbs.twimg.com/profile_images/1148685489...,...,[Lionel46294550],[1030881852486307840],8.0,11.0,67.0,"[rt, lionel, xrp, xrpcommunity, btc, eth, ltc,...",0.0,0.842,0.158,0.4927
4997,2019-10-27 13:41:29+00:00,Ajneri4,RT @CoinEmergency: Hmm $BTC...do YOU want $20 ...,1188450649010126848,en,5150,239,972,"Cagayan De Oro City, Northern",http://pbs.twimg.com/profile_images/1183553750...,...,"[CoinEmergency, CoinEmergency]","[1010151437224022022, 1010151437224022022]",NaN,NaN,NaN,"[rt, coinemergency, hmm, btcdo, want, rt, like...",0.0,0.588,0.412,0.7184
4998,2019-10-27 13:41:29+00:00,lightifyco1,RT @webnowcompany: The worldâ€™s leading Bitcoin...,1188450648842493953,en,8675,1114,60,"California, USA",http://pbs.twimg.com/profile_images/7345596857...,...,[webnowcompany],[1052519189989269504],NaN,NaN,NaN,"[rt, webnowcompany, world, leading, bitcoin, c...",0.0,0.738,0.262,0.4939
4999,2019-10-27 13:41:25+00:00,CryptoFozzie,RT @_blockandchain_: Crypto Twitter be like......,1188450632287637505,en,986,115,501,MuppetMewn,http://pbs.twimg.com/profile_images/1144121445...,...,[_blockandchain_],[954018392146526208],NaN,NaN,NaN,"[rt, blockandchain, crypto, twitter, likebitcoin]",0.0,1.000,0.000,0.0000

In [3]:
#unpickled_df2 = pd.read_pickle("../../data/clean/twitter_sentiment2.pkl")
#unpickled_df2

In [4]:
price_data = pd.read_csv("../../data/price_data/bitcoin_hourly.csv", index_col="date_time")
price_data

                       close  volumefrom
date_time
2019-10-15 00:00:00  8378.45     1464.67
2019-10-15 01:00:00  8342.38      464.00
2019-10-15 02:00:00  8351.43      487.40
2019-10-15 03:00:00  8329.13      332.29
2019-10-15 04:00:00  8350.23      528.90
...                      ...         ...
2019-10-31 19:00:00  9251.18      796.60
2019-10-31 20:00:00  9197.68     1888.84
2019-10-31 21:00:00  9144.69     4624.81
2019-10-31 22:00:00  9136.74      846.99
2019-10-31 23:00:00  9157.52      601.09

[408 rows x 2 columns]

In [5]:
#price_data.groupby(pd.Grouper(key='date_time', freq='60m', axis=1))

In [6]:
#head=unpickled_df.head(10)

In [7]:
#head

In [8]:
#test_df = unpickled_df[['created_at', 'compound', 'id', 'user_favourites_count', 'screen_name']].copy()
#test_df

In [10]:
#test = test_df.drop_duplicates(subset=['compound'])
#test

In [11]:
#binned_df = test_df.groupby([test_df['created_at'].dt.to_period('H'), 'user_favourites_count']).count().unstack()
# Droping unnecessary column level
#binned_df.columns = binned_df.columns.droplevel()
#binned_df.plot(kind='bar', legend=False)

In [12]:
#binned_df

In [18]:
#grouped_df = test_df.groupby([test_df['created_at'].dt.to_period('H'), 'user_favourites_count', 'screen_name', 'compound', 'id'])
#big_df

In [16]:
#df = pd.DataFrame(grouped_df.size().reset_index(level=['created_at']))
#df

In [40]:
#df.to_csv('model.csv')

In [8]:
#binned_d = price_data.groupby([price_data['date_time'].dt.to_period('D'), 'close']).count().unstack()
# Droping unnecessary column level
#binned_d.columns = binned_d.columns.droplevel()
#binned_d.plot(kind='bar')

AttributeError: Can only use .dt accessor with datetimelike values

In [17]:
model_data = unpickled_df[['created_at', 'negative', 'neutral', 'positive', 'clean_tokens']].copy()
model_data

,created_at,negative,neutral,positive,clean_tokens
0,2019-10-31 23:58:56+00:00,1.000,0.000,0.0000,"[rt, deltaexchange, many, coin, logo, see, ima..."
1,2019-10-31 23:58:56+00:00,0.865,0.135,0.3612,"[rt, xrpcryptowolf, intercontinental, exchange..."
2,2019-10-31 23:58:55+00:00,1.000,0.000,0.0000,"[bitcoin, need, real, use, case, become, digit..."
3,2019-10-31 23:58:52+00:00,0.732,0.268,0.5106,"[cyhchloe, johnkim, jasminecoin, codeyisfun, c..."
4,2019-10-31 23:58:50+00:00,1.000,0.000,0.0000,"[rt, zerohedge, year, ago, today, satoshi, nak..."
...,...,...,...,...,...
4995,2019-10-27 13:41:36+00:00,0.448,0.552,0.9062,"[rt, satasion, giveaway, alert, halloween, edi..."
4996,2019-10-27 13:41:34+00:00,0.842,0.158,0.4927,"[rt, lionel, xrp, xrpcommunity, btc, eth, ltc,..."
4997,2019-10-27 13:41:29+00:00,0.588,0.412,0.7184,"[rt, coinemergency, hmm, btcdo, want, rt, like..."
4998,2019-10-27 13:41:29+00:00,0.738,0.262,0.4939,"[rt, webnowcompany, world, leading, bitcoin, c..."
4999,2019-10-27 13:41:25+00:00,1.000,0.000,0.0000,"[rt, blockandchain, crypto, twitter, likebitcoin]"

In [21]:
#bins by the hour
grouped_model = model_data.groupby([model_data['created_at'].dt.to_period('H'), 'negative', 'positive', 'neutral'])

In [24]:
#change groupbyDataFrame to regular df
model_df = pd.DataFrame(grouped_model.size().reset_index(level=['created_at']))
model_df

                                 created_at    0
negative positive neutral
0.224     0.6597  0.448    2019-10-27 13:00    1
0.248    -0.8934  0.268    2019-10-27 13:00    1
0.286     0.3612  0.714    2019-10-27 13:00    1
0.316    -0.9042  0.168    2019-10-27 13:00    1
          0.8689  0.684    2019-10-27 13:00    1
...                                     ...  ...
0.922     0.3182  0.078    2019-10-31 23:00    1
0.925     0.3612  0.075    2019-10-31 23:00    1
0.936     0.1280  0.064    2019-10-31 23:00    1
0.950     0.0258  0.050    2019-10-31 23:00    1
1.000     0.0000  0.000    2019-10-31 23:00  237

[2225 rows x 2 columns]